#!/usr/bin/env python3
"""Generate a deterministic DNS corpus for the OpenStack bench."""

import argparse
import json
import random
from pathlib import Path


PROFILES = {
    "bootstrap": (
        ("hot_a", 450),
        ("warm_a", 200),
        ("cold_a", 100),
        ("aaaa", 100),
        ("unsupported", 50),
        ("nxdomain", 50),
        ("cname", 30),
        ("truncated", 20),
    ),
    # The top-three qtype profile is expressed in basis points of 1000.  The
    # A total includes its A/NXDOMAIN/CNAME queries: 536 + 20 + 10 = 566.
    # The remaining 68 are TXT/other fail-open traffic.
    "top3": (
        ("hot_a", 350),
        ("warm_a", 120),
        ("cold_a", 66),
        ("aaaa", 303),
        ("https", 63),
        ("unsupported", 50),
        ("nxdomain", 20),
        ("cname", 10),
        ("truncated", 18),
    ),
    # Cloudflare Radar, DNS queries to 1.1.1.1 from the Netherlands.  The
    # public dashboard reported this seven-day query-type distribution when
    # the profile was captured: A 56.6%, AAAA 30.3%, HTTPS 6.3%, PTR 3.6%,
    # NS 0.7%, Other 2.5%.  A is split into the same positive/negative shapes
    # used by the existing top3 corpus; the aggregate QTYPE share remains
    # exactly 56.6%.
    "radar-nl": (
        ("hot_a", 350),
        ("warm_a", 120),
        ("cold_a", 66),
        ("aaaa", 303),
        ("https", 63),
        ("ptr", 36),
        ("ns", 7),
        ("other", 25),
        ("nxdomain", 20),
        ("cname", 10),
    ),
    # Exact marginal distributions from the Cloudflare Radar Netherlands DNS
    # dashboard captured on 2026-08-13.  This profile is generated by the
    # dedicated path below because it preserves QTYPE, RCODE and resolver
    # cache-status marginals independently (the dashboard does not publish
    # their joint distribution).
    "radar-nl-observed": (),
    # A-only mechanism profiles generated by dedicated paths below.  Radar
    # publishes cache-hit and QTYPE marginals separately, so conditioning the
    # 78.5/21.5 split on A is an explicit benchmark hypothesis.
    "radar-a-observed": (),
    "a-all-hit": (),
    "a-all-miss": (),
    # Radar's observed non-A QTYPE mix, renormalized after removing A.  No
    # cache entries for these query names are installed.
    "radar-non-a-observed": (),
    # Synthetic response-shape control requested for fail-open validation.
    "fail-open-aaaa-nxdomain-cname": (),
}

RADAR_NL_QTYPE_WEIGHTS = (
    ("A", 5660),
    ("AAAA", 3030),
    ("HTTPS", 630),
    ("PTR", 360),
    ("NS", 70),
    ("Other", 250),
)
RADAR_NL_RCODE_WEIGHTS = (
    ("NOERROR", 8860),
    ("NXDOMAIN", 1000),
    ("SERVFAIL", 130),
    ("NOTIMP", 10),
)
RADAR_NL_CACHE_WEIGHTS = (("hit", 7850), ("miss", 2150))
RADAR_NL_BASIS = 10000


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--cache-output")
    parser.add_argument("--domain", default="openstack.example.test")
    parser.add_argument("--lines", type=int, default=50000)
    parser.add_argument("--seed", type=int, default=20260805)
    parser.add_argument("--profile", choices=sorted(PROFILES), default="bootstrap")
    return parser.parse_args()


def skewed_index(rng, pool_size):
    """A stable heavy-head distribution without third-party dependencies."""
    return min(pool_size - 1, int((rng.random() ** 3.0) * pool_size))


def exact_marginal_rows(weights, lines, basis, label):
    if lines % basis:
        raise SystemExit(
            f"--lines must be divisible by {basis} for {label} exact marginals"
        )
    rows = []
    for name, weight in weights:
        rows.extend([name] * (lines * weight // basis))
    if len(rows) != lines:
        raise RuntimeError(f"{label} weights do not sum to {basis}")
    return rows


def write_outputs(args, rows, cache_entries, manifest):
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(row for _, row in rows) + "\n", encoding="ascii"
    )

    manifest_path = Path(args.manifest)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="ascii"
    )
    if args.cache_output:
        cache_path = Path(args.cache_output)
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        cache_lines = "\n".join(
            " ".join(entry) for entry in sorted(cache_entries)
        )
        cache_path.write_text(
            cache_lines + ("\n" if cache_lines else ""), encoding="ascii"
        )


def generate_radar_observed(args, domain, rng):
    qtypes = exact_marginal_rows(
        RADAR_NL_QTYPE_WEIGHTS, args.lines, RADAR_NL_BASIS, "QTYPE"
    )
    rcodes = exact_marginal_rows(
        RADAR_NL_RCODE_WEIGHTS, args.lines, RADAR_NL_BASIS, "RCODE"
    )
    cache_states = exact_marginal_rows(
        RADAR_NL_CACHE_WEIGHTS, args.lines, RADAR_NL_BASIS, "cache status"
    )
    # Radar publishes each marginal, but not QTYPE x RCODE x cache status.
    # Independent deterministic shuffles make that assumption explicit and
    # preserve every published marginal exactly.
    rng.shuffle(qtypes)
    rng.shuffle(rcodes)
    rng.shuffle(cache_states)

    descriptors = [
        {"qtype": qtype, "rcode": rcode, "cache": cache_state, "direct": False}
        for qtype, rcode, cache_state in zip(qtypes, rcodes, cache_states)
    ]

    # Radar also publishes whether NOERROR A and AAAA responses contain a
    # non-empty answer.  Apply those exact rates within the synthesized joint
    # cells.  HTTPS has no equivalent published metric; direct HTTPS answers
    # are an explicitly documented benchmark fixture.
    for qtype, weight in (("A", 896), ("AAAA", 445)):
        candidates = [
            index
            for index, descriptor in enumerate(descriptors)
            if descriptor["qtype"] == qtype and descriptor["rcode"] == "NOERROR"
        ]
        rng.shuffle(candidates)
        direct_count = round(len(candidates) * weight / 1000)
        for index in candidates[:direct_count]:
            descriptors[index]["direct"] = True
    for descriptor in descriptors:
        if descriptor["qtype"] == "HTTPS" and descriptor["rcode"] == "NOERROR":
            descriptor["direct"] = True

    pools = {"A": 256, "AAAA": 256, "HTTPS": 128, "PTR": 128, "NS": 64, "Other": 128}
    type_tokens = {"A": "A", "AAAA": "AAAA", "HTTPS": "HTTPS", "PTR": "PTR", "NS": "NS", "Other": "TXT"}
    cache_values = {
        "A": ("10.0.0.123", "3600"),
        "AAAA": ("2001:db8::123", "3600"),
        "HTTPS": ("000100", "3600"),
    }
    hot_prefixes = {"A": "hot", "AAAA": "v6", "HTTPS": "https", "PTR": "ptr", "NS": "ns", "Other": "other"}
    cache_entries = set()
    rows = []
    category_counts = {}
    direct_counts = {"A": 0, "AAAA": 0, "HTTPS": 0}
    preload_hits = {"xpress": 0, "linux_accel": 0}
    cold_indexes = {qtype: 0 for qtype, _ in RADAR_NL_QTYPE_WEIGHTS}
    failure_indexes = {rcode: 0 for rcode, _ in RADAR_NL_RCODE_WEIGHTS}

    for descriptor in descriptors:
        qtype = descriptor["qtype"]
        rcode = descriptor["rcode"]
        cache_state = descriptor["cache"]
        token = type_tokens[qtype]
        if rcode != "NOERROR":
            prefix = {"NXDOMAIN": "nxd", "SERVFAIL": "servfail", "NOTIMP": "notimp"}[rcode]
            index = failure_indexes[rcode]
            failure_indexes[rcode] += 1
            name = f"{prefix}-{qtype.lower()}-{index:06d}.{domain}"
            category = rcode.lower()
        elif descriptor["direct"]:
            direct_counts[qtype] += 1
            if cache_state == "hit":
                index = skewed_index(rng, pools[qtype])
                name = f"{hot_prefixes[qtype]}-{index:04d}.{domain}"
                category = f"{qtype.lower()}_direct_hit"
                preload_hits["linux_accel"] += 1
                value, ttl = cache_values[qtype]
                cache_entries.add((name, qtype, value, ttl))
                if qtype == "A":
                    preload_hits["xpress"] += 1
            else:
                index = cold_indexes[qtype]
                cold_indexes[qtype] += 1
                prefix = {"A": "cold", "AAAA": "v6-cold", "HTTPS": "https-cold"}[qtype]
                name = f"{prefix}-{index:06d}.{domain}"
                category = f"{qtype.lower()}_direct_miss"
        elif qtype in ("A", "AAAA"):
            index = cold_indexes[qtype]
            cold_indexes[qtype] += 1
            name = f"empty-{qtype.lower()}-{index:06d}.{domain}"
            category = f"{qtype.lower()}_empty"
        else:
            if cache_state == "hit":
                index = skewed_index(rng, pools[qtype])
            else:
                index = cold_indexes[qtype]
                cold_indexes[qtype] += 1
            name = f"{hot_prefixes[qtype]}-{index:06d}.{domain}"
            category = f"{qtype.lower()}_{cache_state}"
        rows.append((category, f"{name} {token}"))
        category_counts[category] = category_counts.get(category, 0) + 1

    # Shuffle complete rows once more so short smoke tests sample every
    # marginal instead of inheriting construction order.
    rng.shuffle(rows)
    qtype_counts = {name: qtypes.count(name) for name, _ in RADAR_NL_QTYPE_WEIGHTS}
    rcode_counts = {name: rcodes.count(name) for name, _ in RADAR_NL_RCODE_WEIGHTS}
    cache_counts = {name: cache_states.count(name) for name, _ in RADAR_NL_CACHE_WEIGHTS}
    manifest = {
        "domain": domain,
        "lines": len(rows),
        "seed": args.seed,
        "profile": args.profile,
        "profile_basis": RADAR_NL_BASIS,
        "qtype_counts": qtype_counts,
        "qtype_percentages": {name: weight / 100 for name, weight in RADAR_NL_QTYPE_WEIGHTS},
        "rcode_counts": rcode_counts,
        "rcode_percentages": {name: weight / 100 for name, weight in RADAR_NL_RCODE_WEIGHTS},
        "resolver_cache_counts": cache_counts,
        "resolver_cache_percentages": {name: weight / 100 for name, weight in RADAR_NL_CACHE_WEIGHTS},
        "category_counts": category_counts,
        "direct_answer_counts": direct_counts,
        "cache_entries": len(cache_entries),
        "preloaded_hit_percent": round(100 * preload_hits["linux_accel"] / len(rows), 3),
        "xpress_preloaded_hit_percent": round(100 * preload_hits["xpress"] / len(rows), 3),
        "captured_on": "2026-08-13",
        "source_url": "https://radar.cloudflare.com/dns/nl",
        "source": "Cloudflare Radar Netherlands 1.1.1.1 seven-day dashboard snapshot",
        "synthesis": {
            "joint_distribution": "independent deterministic shuffle of published marginals",
            "A_nonempty_given_noerror_percent": 89.6,
            "AAAA_nonempty_given_noerror_percent": 44.5,
            "HTTPS_direct_answer": "fixture assumption; Radar does not publish a non-empty HTTPS-answer rate",
            "hot_name_popularity": "synthetic power-law (random**3), not a production domain trace",
            "cache_mapping": "Radar resolver cache hit/miss is used as a locality proxy; only direct supported records are preloaded into accelerator maps",
        },
        "notes": [
            "synthetic corpus preserving published marginals; not a packet trace",
            "REFUSED and FORMERR are each reported as <0.1% and omitted because no exact share is published",
            "encrypted DNS transport shares are documented separately; this XDP benchmark carries the UDP subset only",
        ],
    }
    write_outputs(args, rows, cache_entries, manifest)


def generate_a_control(args, domain, rng):
    if args.profile == "radar-a-observed":
        if args.lines % RADAR_NL_BASIS:
            raise SystemExit(
                f"--lines must be divisible by {RADAR_NL_BASIS} for exact "
                "Radar cache-hit marginals"
            )
        hit_count = args.lines * 7850 // RADAR_NL_BASIS
        source = "Cloudflare Radar NL resolver cache marginal, conditioned on A by benchmark hypothesis"
    elif args.profile == "a-all-hit":
        hit_count = args.lines
        source = "mechanism control"
    else:
        hit_count = 0
        source = "mechanism control"
    miss_count = args.lines - hit_count

    hot_pool = 256
    cache_entries = set()
    if hit_count:
        for index in range(hot_pool):
            cache_entries.add(
                (f"hot-{index:04d}.{domain}", "A", "10.0.0.123", "3600")
            )
    else:
        # Xpress's loader requires at least one A record.  Keep an explicitly
        # unused entry so the measured request stream remains a true 0%-hit
        # workload in both implementations.
        cache_entries.add(
            (f"unused-0000.{domain}", "A", "10.0.0.123", "3600")
        )

    rows = []
    for _ in range(hit_count):
        index = skewed_index(rng, hot_pool)
        rows.append(("a_direct_hit", f"hot-{index:04d}.{domain} A"))
    for index in range(miss_count):
        rows.append(("a_direct_miss", f"cold-{index:06d}.{domain} A"))
    rng.shuffle(rows)

    hit_percent = round(100 * hit_count / args.lines, 3)
    manifest = {
        "domain": domain,
        "lines": len(rows),
        "seed": args.seed,
        "profile": args.profile,
        "profile_basis": RADAR_NL_BASIS,
        "qtype_counts": {"A": args.lines},
        "qtype_percentages": {"A": 100.0},
        "resolver_cache_counts": {"hit": hit_count, "miss": miss_count},
        "resolver_cache_percentages": {
            "hit": hit_percent,
            "miss": round(100 - hit_percent, 3),
        },
        "category_counts": {
            "a_direct_hit": hit_count,
            "a_direct_miss": miss_count,
        },
        "cache_entries": len(cache_entries),
        "preloaded_hit_percent": hit_percent,
        "xpress_preloaded_hit_percent": hit_percent,
        "captured_on": "2026-08-13" if args.profile == "radar-a-observed" else None,
        "source_url": "https://radar.cloudflare.com/dns/nl" if args.profile == "radar-a-observed" else None,
        "source": source,
        "synthesis": {
            "cache_mapping": "Radar resolver cache hit/miss mapped to preloaded/unpreloaded A names",
            "conditioning": "A-only cache split is a hypothesis; Radar does not publish QTYPE x cache status",
            "hot_name_popularity": "synthetic power-law (random**3), not a production domain trace",
            "unused_loader_entry": not bool(hit_count),
        },
        "notes": [
            "synthetic mechanism-control corpus; not a packet trace",
            "both Xpress and linux_accel receive the same A-record cache file",
        ],
    }
    write_outputs(args, rows, cache_entries, manifest)


def generate_radar_non_a(args, domain, rng):
    non_a_weights = tuple(
        (name, weight) for name, weight in RADAR_NL_QTYPE_WEIGHTS if name != "A"
    )
    basis = sum(weight for _, weight in non_a_weights)
    qtypes = exact_marginal_rows(non_a_weights, args.lines, basis, "non-A QTYPE")
    rng.shuffle(qtypes)
    tokens = {"AAAA": "AAAA", "HTTPS": "HTTPS", "PTR": "PTR", "NS": "NS", "Other": "TXT"}
    prefixes = {"AAAA": "v6-cold", "HTTPS": "https-cold", "PTR": "ptr", "NS": "ns", "Other": "other"}
    indexes = {name: 0 for name, _ in non_a_weights}
    rows = []
    for qtype in qtypes:
        index = indexes[qtype]
        indexes[qtype] += 1
        rows.append(
            (
                f"{qtype.lower()}_pass",
                f"{prefixes[qtype]}-{index:06d}.{domain} {tokens[qtype]}",
            )
        )
    cache_entries = {
        (f"unused-0000.{domain}", "A", "10.0.0.123", "3600")
    }
    manifest = {
        "domain": domain,
        "lines": len(rows),
        "seed": args.seed,
        "profile": args.profile,
        "profile_basis": basis,
        "qtype_counts": {name: qtypes.count(name) for name, _ in non_a_weights},
        "qtype_percentages": {
            name: round(100 * weight / basis, 6)
            for name, weight in non_a_weights
        },
        "category_counts": {
            f"{name.lower()}_pass": qtypes.count(name)
            for name, _ in non_a_weights
        },
        "cache_entries": len(cache_entries),
        "preloaded_hit_percent": 0.0,
        "xpress_preloaded_hit_percent": 0.0,
        "captured_on": "2026-08-13",
        "source_url": "https://radar.cloudflare.com/dns/nl",
        "source": "Cloudflare Radar NL QTYPE marginal renormalized after removing A",
        "synthesis": {
            "conditioning": "non-A shares renormalized from the published QTYPE marginal",
            "cache_mapping": "no queried name is preloaded; one unused A entry only satisfies the Xpress loader",
        },
        "notes": [
            "all requests exercise a forwarding path in both accelerators",
            "AAAA and HTTPS are implementation-supported types but deliberately unpreloaded",
        ],
    }
    write_outputs(args, rows, cache_entries, manifest)


def generate_fail_open_shapes(args, domain, rng):
    if args.lines % 10:
        raise SystemExit("--lines must be divisible by 10 for fail-open profile")
    counts = {
        "aaaa": args.lines * 4 // 10,
        "nxdomain": args.lines * 3 // 10,
        "cname": args.lines * 3 // 10,
    }
    rows = []
    rows.extend(
        ("aaaa", f"v6-cold-{index:06d}.{domain} AAAA")
        for index in range(counts["aaaa"])
    )
    rows.extend(
        ("nxdomain", f"nxd-a-{index:06d}.{domain} A")
        for index in range(counts["nxdomain"])
    )
    rows.extend(
        ("cname", f"cname-{index:06d}.{domain} A")
        for index in range(counts["cname"])
    )
    rng.shuffle(rows)
    cache_entries = {
        (f"unused-0000.{domain}", "A", "10.0.0.123", "3600")
    }
    manifest = {
        "domain": domain,
        "lines": len(rows),
        "seed": args.seed,
        "profile": args.profile,
        "profile_basis": 10,
        "qtype_counts": {
            "A": counts["nxdomain"] + counts["cname"],
            "AAAA": counts["aaaa"],
        },
        "qtype_percentages": {"A": 60.0, "AAAA": 40.0},
        "category_counts": counts,
        "cache_entries": len(cache_entries),
        "preloaded_hit_percent": 0.0,
        "xpress_preloaded_hit_percent": 0.0,
        "source": "synthetic fail-open response-shape control",
        "synthesis": {
            "shape_mix": "40% AAAA direct answer, 30% NXDOMAIN, 30% CNAME+A",
            "cache_mapping": "no queried name is preloaded",
        },
        "notes": [
            "not a production distribution",
            "isolates forwarding correctness and XDP miss-path overhead",
        ],
    }
    write_outputs(args, rows, cache_entries, manifest)


def main():
    args = parse_args()
    if args.lines < 100 or args.lines % 100:
        raise SystemExit("--lines must be at least 100 and divisible by 100")
    domain = args.domain.rstrip(".").lower()
    rng = random.Random(args.seed)
    if args.profile == "radar-nl-observed":
        generate_radar_observed(args, domain, rng)
        return
    if args.profile in ("radar-a-observed", "a-all-hit", "a-all-miss"):
        generate_a_control(args, domain, rng)
        return
    if args.profile == "radar-non-a-observed":
        generate_radar_non_a(args, domain, rng)
        return
    if args.profile == "fail-open-aaaa-nxdomain-cname":
        generate_fail_open_shapes(args, domain, rng)
        return
    profile = PROFILES[args.profile]
    categories = {
        "hot_a",
        "warm_a",
        "cold_a",
        "aaaa",
        "https",
        "unsupported",
        "nxdomain",
        "cname",
        "truncated",
        "ptr",
        "ns",
        "other",
    }
    counts = {name: 0 for name in categories}
    counts.update(
        {name: args.lines * weight // 1000 for name, weight in profile}
    )
    counts["hot_a"] += args.lines - sum(counts.values())
    rows = []
    cache_entries = set()

    # Keep the cacheable working set below the project's 1024-entry map for
    # the Radar comparison.  The corpus still contains 50k requests and a
    # heavy head; only the number of unique hot names is bounded.
    radar_pool_sizes = {
        "hot_a": 128,
        "warm_a": 256,
        "aaaa": 256,
        "https": 128,
    }
    hot_pool = (
        radar_pool_sizes["hot_a"]
        if args.profile == "radar-nl"
        else min(500, max(32, counts["hot_a"] // 20))
    )
    if args.profile == "radar-nl":
        for index in range(hot_pool):
            cache_entries.add(
                (f"hot-{index:04d}.{domain}", "A", "10.0.0.123", "3600")
            )
    for _ in range(counts["hot_a"]):
        index = skewed_index(rng, hot_pool)
        name = f"hot-{index:04d}.{domain}"
        rows.append(("hot_a", f"{name} A"))
        cache_entries.add((name, "A", "10.0.0.123", "3600"))

    warm_pool = (
        radar_pool_sizes["warm_a"]
        if args.profile == "radar-nl"
        else min(5000, max(256, counts["warm_a"] // 2))
    )
    if args.profile == "radar-nl":
        for index in range(warm_pool):
            cache_entries.add(
                (f"warm-{index:05d}.{domain}", "A", "10.0.0.123", "3600")
            )
    for _ in range(counts["warm_a"]):
        index = skewed_index(rng, warm_pool)
        name = f"warm-{index:05d}.{domain}"
        rows.append(("warm_a", f"{name} A"))
        cache_entries.add((name, "A", "10.0.0.123", "3600"))

    for index in range(counts["cold_a"]):
        rows.append(("cold_a", f"cold-{index:06d}.{domain} A"))

    v6_pool = (
        radar_pool_sizes["aaaa"]
        if args.profile == "radar-nl"
        else min(1000, max(64, counts["aaaa"] // 5))
    )
    if args.profile == "radar-nl":
        for index in range(v6_pool):
            cache_entries.add(
                (f"v6-{index:04d}.{domain}", "AAAA", "2001:db8::123", "3600")
            )
    for _ in range(counts["aaaa"]):
        index = skewed_index(rng, v6_pool)
        name = f"v6-{index:04d}.{domain}"
        rows.append(("aaaa", f"{name} AAAA"))
        cache_entries.add((name, "AAAA", "2001:db8::123", "3600"))

    https_pool = (
        radar_pool_sizes["https"]
        if args.profile == "radar-nl"
        else min(1000, max(64, counts["https"] // 5))
    )
    if args.profile == "radar-nl":
        for index in range(https_pool):
            cache_entries.add(
                (f"https-{index:04d}.{domain}", "HTTPS", "000100", "3600")
            )
    for _ in range(counts["https"]):
        index = skewed_index(rng, https_pool)
        name = f"https-{index:04d}.{domain}"
        rows.append(("https", f"{name} HTTPS"))
        cache_entries.add((name, "HTTPS", "000100", "3600"))

    # dnsperf cannot toggle EDNS per row.  The unsupported-QTYPE stream is the
    # fail-open stand-in for that traffic; EDNS gets a separate smoke.
    unsupported_pool = min(1000, max(64, counts["unsupported"] // 2))
    for _ in range(counts["unsupported"]):
        index = skewed_index(rng, unsupported_pool)
        rows.append(("unsupported", f"unsupported-{index:04d}.{domain} TXT"))

    for index in range(counts["nxdomain"]):
        rows.append(("nxdomain", f"nxd-{index:05d}.{domain} A"))

    cname_pool = min(500, max(32, counts["cname"] // 4))
    for _ in range(counts["cname"]):
        index = skewed_index(rng, cname_pool)
        rows.append(("cname", f"cname-{index:04d}.{domain} A"))

    for index in range(counts["truncated"]):
        rows.append(("truncated", f"large-{index:05d}.{domain} TXT"))

    ptr_pool = min(512, max(64, counts.get("ptr", 0) // 4))
    for _ in range(counts.get("ptr", 0)):
        index = skewed_index(rng, ptr_pool)
        rows.append(("ptr", f"ptr-{index:04d}.{domain} PTR"))

    ns_pool = min(128, max(32, counts.get("ns", 0) // 2))
    for _ in range(counts.get("ns", 0)):
        index = skewed_index(rng, ns_pool)
        rows.append(("ns", f"ns-{index:04d}.{domain} NS"))

    other_pool = min(256, max(64, counts.get("other", 0) // 3))
    for _ in range(counts.get("other", 0)):
        index = skewed_index(rng, other_pool)
        rows.append(("other", f"other-{index:04d}.{domain} TXT"))

    rng.shuffle(rows)
    manifest = {
        "domain": domain,
        "lines": len(rows),
        "seed": args.seed,
        "profile": args.profile,
        "profile_basis": 1000,
        "profile_weights": dict(profile),
        "counts": counts,
        "qtype_percentages": {
            "A": round(1000 * (counts["hot_a"] + counts["warm_a"] + counts["cold_a"] + counts["nxdomain"] + counts["cname"]) / len(rows) / 10, 1),
            "AAAA": round(1000 * counts["aaaa"] / len(rows) / 10, 1),
            "HTTPS": round(1000 * counts["https"] / len(rows) / 10, 1),
            "PTR": round(1000 * counts.get("ptr", 0) / len(rows) / 10, 1),
            "NS": round(1000 * counts.get("ns", 0) / len(rows) / 10, 1),
            "Other": round(1000 * (counts.get("other", 0) + counts["unsupported"] + counts["truncated"]) / len(rows) / 10, 1),
        },
        "cache_eligible_percent": round(100 * (counts["hot_a"] + counts["warm_a"] + counts["cold_a"] + counts["aaaa"] + counts["https"]) / len(rows), 1),
        "hot_repeat_percent": round(100 * counts["hot_a"] / len(rows), 1),
        "notes": [
            f"{args.profile} synthetic profile; not a production trace",
            "unsupported QTYPE is the per-row stand-in for EDNS/other types",
            "HTTPS rows use one direct HTTPS/IN RR with priority 1 and root target",
            "cold A names are unique within one corpus pass",
        ],
        "cache_entries": len(cache_entries),
        "preloaded_hit_percent": round(
            100
            * (
                counts["hot_a"]
                + counts["warm_a"]
                + counts["aaaa"]
                + counts["https"]
            )
            / len(rows),
            1,
        ),
        "xpress_preloaded_hit_percent": round(
            100 * (counts["hot_a"] + counts["warm_a"]) / len(rows), 1
        ),
        "captured_on": "2026-08-13" if args.profile == "radar-nl" else None,
        "source_url": (
            "https://radar.cloudflare.com/dns/nl"
            if args.profile == "radar-nl"
            else None
        ),
        "source": (
            "Cloudflare Radar Netherlands 1.1.1.1 DNS query-type distribution, seven-day dashboard snapshot"
            if args.profile == "radar-nl"
            else None
        ),
    }
    write_outputs(args, rows, cache_entries, manifest)


if __name__ == "__main__":
    main()
