#ifndef YUKINONET_LDAP_SOCKMAP_ABI_H
#define YUKINONET_LDAP_SOCKMAP_ABI_H

#include <linux/types.h>

#define LDAP_SOCKMAP_MAX_CONNECTIONS 65536

enum ldap_sockmap_stat_key {
    LDAP_SOCKMAP_STAT_STREAM = 0,
    LDAP_SOCKMAP_STAT_REDIRECT,
    LDAP_SOCKMAP_STAT_PEER_MISS,
    LDAP_SOCKMAP_STAT_REDIRECT_FAIL,
    LDAP_SOCKMAP_STAT_COUNT,
};

#endif
